pub mod addyio;
pub mod duckduckgo;
pub mod fastmail;
pub mod firefox;
pub mod forwardemail;
pub mod simplelogin;

// Common helper functions
pub fn format_description(website: &Option<String>) -> String {
    if let Some(website) = website {
        format!("Generated by Bitwarden for {}", website)
    } else {
        "Generated by Bitwarden".to_string()
    }
}

pub fn format_description_ff(website: &Option<String>) -> String {
    website.clone().unwrap_or_else(|| "Generated by Bitwarden".to_string())
} 